### ISSUE TITLE
Instructivo de instalación

### ISSUE THREAD

**Issue by creyes-dev** [argob/AR-Distro#1]
Gracias por el instructivo de instalación utilizando Centos 6, seguí todos los pasos y me encontré con un problema que pude resolver como les comento a continuación:

Mi instrucción para ejecutar el script fue sh scripts/build.sh /var/www/html por lo tanto dejé todos los archivos en el Document Root de apache, luego cambié los permisos de los archivos instalados con chmod 755 -R /var/www/html, luego cambié la configuración del directorio del apache con lo siguiente:

DocumentRoot "/var/www/html"
<Directory />
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

Pero aun luego de reiniciar al escribir localhost el navegador me mostraba una página con el siguiente texto: You don't have permission to access (nombre del archivo) on this server

El problema fue solucionando escribiendo
sudo restorecon -r /var/www/html

Y magia! ya pude instalar drupal con la distribución. 

Gracias, saludos!

**Comment by Sophivorus** [comment]
@creyes-dev Hola Cristian! Gracias por tu aporte, me gustaría incorporarlo al instructivo para evitar que otros tengan el mismo inconveniente, pero no termino de entender si el problema que te encontraste se debe a algún cambio o configuración que hayas hecho en tu instancia antes de intentar instalar la AR-Distro, o si es un problema que en principio puede surgir a cualquiera que intente instalar AR-Distro en una instancia nueva.

**Comment by creyes-dev** [comment]
comencé a seguir los pasos del instructivo inmediatamente después de finalizar la instalación de centos 6.9, preferí instalar la versión que viene en dvd en vez de la versión mínima y la versión que usé instala y configura un servidor apache, luego de ejecutar el script para generar la distribución de drupal tuve que hacer los dos cambios que te comenté. 

No sé si lo siguiente se trata de un problema porque drupal se pudo instalar y configurar correctamente pero el paso "Install profile" o "Perfil de instalación" de la instalación no termina al 100% y muestra el siguiente error: 

SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead 

y al hacer click en el vínculo con el texto Please continue to the error page, se obtiene la siguiente descripción: 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ardistro.languages' doesn't exist 

Pensé que era por instalar la distribución en español, pero luego volví a instalar la distribución en inglés en otro servidor y el error que sale es el mismo

**Comment by Sophivorus** [comment]
@creyes-dev Hola! Ese error yo también me lo crucé, se debe a que tenés instalado MySQL 5.7, pero la AR-Distro requiere MySQL 5.5
